[package]
name = "filefly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
chrono = "0.4.31"
fs_extra = "1.3.0"
walkdir = "2.4.0"
log = "0.4.20"
indicatif = "0.17.7"
tokio = { version = "1", features = ["full"] }
winapi = { version = "0.3.9", features = ["winuser", "shellapi"] }