name: Build and Release Binaries

on:
  push:
    tags:
      - "v*" # Triggers on tags that start with "v" (e.g., v1.0.0)

jobs:
  build:
    name: Build for Windows and Unix-like Systems
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies
        run: cargo fetch

      - name: Build release binary
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: filefly-${{ matrix.os }}
          path: |
            target/release/filefly*
            target/release/filefly.exe*

  release:
    name: Create Release and Upload Binaries
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux binary to release
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/filefly
          asset_name: filefly-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows binary to release
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'windows-latest'
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/filefly.exe
          asset_name: filefly-windows.exe
          asset_content_type: application/octet-stream
